global:
  scrape_interval:     30s
  evaluation_interval: 30s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: price
    static_configs:
      - targets: ['localhost:5000']